### ISSUE TITLE
install taglib-ruby 0.6.0 on windows with ruby 2.0.0p247 (binary gem)

### ISSUE THREAD

**Issue by romusD** [robinst/taglib-ruby#36] opened 2013-08-15 10:40 UTC
D:>gem install taglib-ruby
Fetching: taglib-ruby-0.6.0-x86-mingw32.gem (100%)
Successfully installed taglib-ruby-0.6.0-x86-mingw32
Parsing documentation for taglib-ruby-0.6.0-x86-mingw32
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/libtag.dll, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_base.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_flac.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_id3v1.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_id3v2.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_mp4.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_mpeg.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_ogg.so, skipping
unable to convert "\x90" from ASCII-8BIT to UTF-8 for lib/taglib_vorbis.so, skipping
Installing ri documentation for taglib-ruby-0.6.0-x86-mingw32
1 gem installed

D:>irb
DL is deprecated, please use Fiddle
irb(main):001:0> require 'taglib'
LoadError: 126: The specified module could not be found.   - D:/xampplite/Ruby200/lib/ruby/gems/2.0.0/gems/taglib-ruby-0.6.0-x86-mingw32/lib/taglib_base.so
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
        from D:/xampplite/Ruby200/lib/ruby/gems/2.0.0/gems/taglib-ruby-0.6.0-x86-mingw32/lib/taglib/base.rb:1:in `<top (required)>'
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
        from D:/xampplite/Ruby200/lib/ruby/gems/2.0.0/gems/taglib-ruby-0.6.0-x86-mingw32/lib/taglib.rb:9:in`<top (required)>'
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in`rescue in require'
        from D:/xampplite/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from (irb):1
        from D:/xampplite/Ruby200/bin/irb:12:in`<main>'

**Comment by robinst** [comment] 2017-06-13 04:13
Closing as a duplicate of #62 for fixing Windows somehow.

**Closed by robinst** 2017-06-13 04:13 UTC
